### ISSUE TITLE
Invalid package.json

### ISSUE THREAD

**Issue by baelter** [ninjatronic/angular-base64#10]
Can't install with npm due to invalid package.json

**Comment by ninjatronic** [comment]
The module isn't registered with NPM. NPM installation is not currently supported. Is there a reason you cannot install using bower?

**Comment by baelter** [comment]
I don't like bower. I like npm.

**Comment by ninjatronic** [comment]
See [v2.0.5](https://github.com/ninjatronic/angular-base64/releases/tag/v2.0.5) on [npm](https://www.npmjs.com/package/angular-base64)

**Comment by eranimo** [comment]
Need a `main` attribute for your package.json file to make it browserify compatable.

**Comment by ninjatronic** [comment]
Please open a new issue so I don't forget
