### ISSUE TITLE
not decoding

### ISSUE THREAD

**Issue by ror6ax** [ninjatronic/angular-base64#11]
Hello, I use your lib to encode IP address and pass it to RoR. 
Problem is, when I run Ruby's Base64.decode64 on it, I get this 
��e�+-z

Encoded string is `MTcyLjE4LjAuMTQw`
Raw string is `172.18.0.140`
Any idea what is wrong?
Thanks

**Comment by ninjatronic** [comment]
That string is correctly encoded. You can verify using [this tool](https://www.base64decode.org/). The encoded string you supplied decodes to give `77+977+9Ze+/vSsteg==`. Are you sure you are encoding the right thing?
