### ISSUE TITLE
valid license

### ISSUE THREAD

**Issue by maruilian11** [ninjatronic/angular-base64#14]
hello, recently we want to add your lib on https://cdnjs.com, but we need a clear license field. by follow urls, we guess the type of the license you use is BSD:
https://github.com/ninjatronic/angular-base64/blob/master/LICENSE
https://github.com/client9/stringencoders/blob/master/COPYING

we need to confirm this thing with you, if there is any mistake, please tell me.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/5663

**Comment by ninjatronic** [comment]
Hi,

Thanks for the heads up. I'll join the comment thread you've linked :)
